### ISSUE TITLE
Constant jQuery errors in console ?

### ISSUE THREAD

**Issue by wickedst** [nuxt-community/gtm-module#18]
Hey, is anyone else experiencing this?

Seems to happen throughout the site, would love to know a fix or possible workaround

```
ReferenceError: Can't find variable: jQuery
  at global code(/test/login:2:7)
  at insertBefore([native code])
  at ? (/gtm.js:1432:426)
  at c(/gtm.js:1434:152)
  at Cb(/gtm.js:1285:397)
  at e(/gtm.js:1314:140)
  at ? (/gtm.js:1275:115)
  at ? (/gtm.js:1315:230)
  at ? (/gtm.js:1314:473)
  at nf(/gtm.js:1315:520)
  at pf(/gtm.js:1317:229)
  at hj(/gtm.js:1360:189)
  at gj(/gtm.js:1360:3)
  at ij(/gtm.js:1362:359)
  at push(/gtm.js:1365:97)
  at ? (/gtm.js:1364:153)
  at r(/yaan/_nuxt/96e368a391d3c00e7099.js:2:530466)
```

**Comment by pi0** [comment]
Hi @wickedst. I think this issue is not directly with gtm but a snippet that you are injecting to the page and requires `jQuery` to be in the window. Please read this acticle to know how load jQuery:

https://www.simoahava.com/analytics/google-tag-manager-and-jquery/#load-jquery-using-google-tag-manager

**Comment by wickedst** [comment]
Ahh - I see thanks
