### ISSUE TITLE
this.options.head.noscript.push is not a function

### ISSUE THREAD

**Issue by ionut-badea** [nuxt-community/gtm-module#67]
HI,

Does anyone know about this? It is a bug or I've done something wrong?

It is happening when I try to build the app.

  at ModuleContainer.gtmModule (node_modules/@nuxtjs/gtm/lib/module.js:93:32)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:235:34)
  at node_modules/@nuxt/utils/dist/utils.js:1846:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:55:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:715:5)

Thank you!

**Comment by superbiche** [comment]
I'm having the same kind of issue: 

ERROR  Cannot read property 'find' of undefined
at server.js:11864:43
at promisify (.nuxt/utils.js:259:0)
at server.js:16750:60
at Array.map (<anonymous>)
at beforeRender (.nuxt/server.js:94:0)
at module.exports.__webpack_exports__.default (.nuxt/server.js:289:0)
at processTicksAndRejections (internal/process/task_queues.js:97:5)

The culprit code:  

```js
  ctx.beforeNuxtRender(() => {                                                                                                                                                                                                                                                                                                   
    if (!inits.length && !events.length) {                                                                                                                                                                                                                                                                                       
      return;                                                                                                                                                                                                                                                                                                                    
    }                                                                                                                                                                                                                                                                                                                            
    // Here script is undefined                                                                                                                                                                                                                                                                                                                             
    const gtmScript = ctx.app.head.script.find(s => s.hid == 'gtm-script');                                                                                                                                                                                                                                                      
    gtmScript.innerHTML = `window['${_layer}']=${JSON.stringify(events)};${gtmScript.innerHTML}`;                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                 
    if (inits.length) {                                                                                                                                                                                                                                                                                                          
      gtmScript.innerHTML += `;${JSON.stringify(inits)}.forEach(function(i){window._gtm_inject(i)})`;                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                 
    const gtmIframe = ctx.app.head.noscript.find(s => s.hid == 'gtm-noscript');                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                 
    const renderIframe = id => `<iframe src="https://www.googletagmanager.com/ns.html?id=${id}&" height="0" width="0" style="display:none;visibility:hidden" title="gtm"></iframe>`;                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                 
    if (inits.length) {                                                                                                                                                                                                                                                                                                          
      gtmIframe.innerHTML += inits.map(renderIframe);                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                                            
  });                                                                                                                                                                                                                                                                                                                            
```

I'm initializing GTM manually:  
```js
// plugins/gtm.js

export default function({ app, $config, $gtm, store }) {
  if (app.$featureToggle.toggles.gtm) {
    store.subscribe((mutation, state) => {
      if (mutation.type === 'MARKETPLACE_FETCHED') {
        const gtmIds = [
          ...state.marketplace.google_tag_id,
          $config.gtmMainId,
        ]
        gtmIds.forEach(gtmId => {
          $gtm.init(gtmId)
        })
      }
    })
  }
}
```

**Comment by pi0** [comment]
@superbiche Are you using a function for head inside `nuxt.config`?

**Comment by superbiche** [comment]
@pi0 this is my `head` section: 
```js
  head: {
    ...commonConfig.head,
    title: 'Unic Stay - Book Fast Funnel',
  },
```
`commonConfig.head` comes from there:  
```js
module.exports = {
  mode: 'universal',
  /*
   ** Headers of the page
   */
  head: {
    title: process.env.npm_package_name || '',
    meta: [
      {charset: 'utf-8'},
      {
        name: 'viewport',
        content: 'width=device-width, initial-scale=1',
      },
      {
        hid: 'description',
        name: 'description',
        content: process.env.npm_package_description || '',
      },
    ],
    bodyAttrs: {
      class: ['Site'],
    },
  },
// ...
}
```

I've temporarily used a no SSR plugin approach as a workaround, which kinda works but I'm not sure it has no side effect. 

Thanks for your help

**Comment by ionut-badea** [comment]
Sorry for a late response. I've managed to find what was causing this error. It is the presence of noscript into the head. If it is removed, the build will not throw the error.

**Comment by superbiche** [comment]
@pi0 I guess this should be reopened. Having no `<noscript>` in the `<head>` seems like a workaround to me.
